---
rvm:
- 2.1
node_js:
- "0.10"
install:
- "npm install"
after_success:
  - broccoli build dist
script:
  - npm test
env:
  global:
  - BROCCOLI_ENV=production
  matrix:
    - TEST_SUITE=each-package-tests
