rvm:
- 2.1
node_js:
- '0.10'
install:
- npm install
after_success:
- broccoli build dist
- "./bin/bower_bricksui_build"
script:
- npm test

cache:
  directories:
    - node_modules

env:
  global:
  - BROCCOLI_ENV=production
  - secure: xUbB+Xvhal5c8J8sAtI+5PxG2083bINLgvDSH6gIiVS6C5Da/gAj0dHEKlw4pJ9kGmFWgZ1P5rxL7FCqRVZIdhdV+nuzTybza9eRBVHcc5QYoSQUr2QRagQ0tOJhIqbTF0nDhMu6CdMnwydOo6gjucHViUrEHifFY1aZbaU7RfE=
  matrix:
  - TEST_SUITE=each-package-tests
